### ISSUE TITLE
getTitle() must be of the type string, null returned in

### ISSUE THREAD

**Issue by Naberdz** [lizardmedia/product-attachments-magento2#23]
Have following error: 

`AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Return value of LizardMedia\\ProductAttachment\\Model\\Attachment::getTitle() must be of the type string, null returned in /home/pplazam2/domains/plafondplaza.nl/public_html/app/code/LizardMedia/ProductAttachment/Model/Attachment.php:167\nStack trace:\n#0 /home/pplazam2/domains/plafondplaza.nl/public_html/app/code/LizardMedia/ProductAttachment/Model/AttachmentRepository.php(273): LizardMedia\\ProductAttachment\\Model\\Attachment->getTitle()\n#1 /home/pplazam2/domains/plafondplaza.nl/public_html/app/code/LizardMedia/ProductAttachment/Model/AttachmentRepository.php(258): LizardMedia\\ProductAttachment\\Model\\AttachmentRepository->setBasicFields(Object(LizardMedia\\ProductAttachment\\Model\\Attachment), Object(LizardMedia\\ProductAttachment\\Model\\Attachment))\n#2 /home/pplazam2/domains/plafondplaza.nl/public_html/app/code/LizardMedia/ProductAttachment/Model/AttachmentRepository.php(223): LizardMedia\\ProductAttachment\\Model\\AttachmentRepository->buildAttachment(Object(Lizard...\n', referer: https://plafondplaza.nl/backend/catalog/product/edit/id/543/key/4a319c0dfcd151b03113021bd5b00cbe0a052d9eae9acc4db8379ba8ee716676/`

after this error, was able to save product without any problems.. seem it has something to do with store values ( if you have attachment at store level and not default store )

**Comment by bartoszkubicki** [comment]
@Naberdz Are you sure you have actual codebase?
https://github.com/lizardmedia/product-attachments-magento2/blob/782a3d418813dbdb53b73e7b855aac013b6ac89a/Model/Attachment.php#L153

**Comment by Naberdz** [comment]
it seem to be not the latest : 

```
    /**
     * @return string
     */
    public function getTitle() : string
    {
        return $this->getData(self::TITLE);
    }
```

have it on line 167.

will try to update it.

**Comment by bartoszkubicki** [comment]
@Naberdz I see you have installed it manually. Composer install is suggested way. You will have actual codebase with just `compsoer update <package name>`

**Comment by bartoszkubicki** [comment]
Closing due to inactivity.
